name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    name: Build ${{ matrix.configuration }}

    strategy:
      matrix:
        os: [ windows-latest ]
        configuration: [ Debug, Release ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.200
    - name: Build SpanKeyedCollections
      run: dotnet build src --configuration ${{ matrix.configuration }}
    - name: Run Tests
      if: matrix.configuration == 'Debug'
      run: dotnet test src --no-build
    - name: Save Artifacts
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin\SpanKeyedCollections\${{ matrix.configuration }}\*.nupkg
        if-no-files-found: error
